name: unifor_df_dashboards-python_T1
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip
  # Dependências do sistema para geopandas
  - gdal
  - geos  
  - proj
  - fiona
  # Dependências via pip do pyproject.toml
  - pip:
    - -e .
